AppName: Bitidx

# general form buttons
BackBtnCaption:   Back
BackBtnTitle:     All changes will be lost
CancelBtnCaption: Cancel
CancelBtnTitle:   Cancel current changes
SaveBtnCaption:   Save
SaveBtnTitle:     Save current changes

# default layout

## header
NavSearchPlaceholder: Search by name and description...
NavSearchBtn:  Search
NavAddBtn:     Add
NavSigninBtn:  Sign in
NavSignoutBtn: Sign out

## footer
FooterHomeBtn:   Home
FooterHelpBtn:   Help
FooterSourceBtn: Source
FooterIssuesBtn: Issues

# user
## user profile
EditProfileBtnCaption: Редактировать профиль
EditProfileBtnTitle:   TODO
## user edit profile
BackToProfileBtnCaption: Back to profile
EditUserLegend:  Edit user info...

# search
NoResults: No results

# the release page
DescriptionTab:    Description
NoDescriptionLbl:  Author probably do not added any descriptions yet...
MetadataTab:       Metadata
EditDescBtnCaption: Description
EditDescBtnTitle:   Change release name or description
EditMetaBtnCaption: Metadata
EditMetaBtnTitle:   Change torrent file fields

## the release page - maintainer tab
DeleteBtnCaption:  Delete
DeleteBtnTitle:    Remove this release from tracker

## the release page - download bar
DownloadBarText:   Get this torrent via
TorrentBtnCaption: Torrent
TorrentBtnTitle:   Get torrent file
MagnetBtnCaption:  Magnet
MagnetBtnTitle:    Open magnet link (recommended)

# discussion widget
HdrComments:    comments
HdrNoComments:  no comments
AddCommentBtn:  Add comment

# torrent list widget
ListHashCol:   Hash
ListNameCol:   Name
ListSizeCol:   Size
ListAuthorCol: Author

# the edit description page
EditDescriptionLegend: Edit release description...

# the edit metadata page
EditMetadataLegend: Edit torrent metadata...