AppName:                     Bitidx

# general form buttons
BackBtnCaption:              Back
BackBtnTitle:                All changes will be lost
CancelBtnCaption:            Cancel
CancelBtnTitle:              Cancel current changes
SaveBtnCaption:              Save
SaveBtnTitle:                Save current changes

# default layout
## header
NavSearchPlaceholder:        Search by name and description...
NavSearchBtn:                Search
NavAddBtn:                   Add
NavSigninBtn:                Sign in
NavSignoutBtn:               Sign out
## footer
FooterHomeBtn:               Home
FooterHelpBtn:               Help
FooterSourceBtn:             Source
FooterIssuesBtn:             Issues

# user
UserProfilePageTitle userName@Text: #{userName} — User profile
UserEditPageTitle    userName@Text: #{userName} — Edit your profile
UserMissingPageTitle:        Unknown user
## permissions
LoginRequired:               You need to login to perform this action
PermissionDeniedEdit:        You need editor privileges for this action
PermissionDeniedComment:     You need commenter privileges for this action
## user profile
EditProfileBtnCaption:       Edit profile
EditProfileBtnTitle:         Change your profile information
## user edit profile
BackToProfileBtnCaption:     Back to profile
EditUserLegend:              Edit user info...
EditUserSuccess:             Profile has been modified...

# search
SearchResultsPageTitle query@Text: Search results for #{query} — Bitidx
SearchNoQueryPageTitle:            Search torrent — Bitidx
NoResults:                   No results

# error pages
InvalidTorrentPageTitle:     Invalid torrent file
AlreadyExistPageTitle:       Torrent already exist
FormFailurePageTitle:        Form failure!
NotFoundPageTitle:           Not found...

# the release add page
AddReleasePageTitle:         Add torrent to database — Bitidx
AddReleaseSuccess:           Torrent has been added...
AddReleaseLegend:            Upload new torrent file...
TorrentFileLabel:            Torrent
AddReleaseBtnCaption:        Add
AddReleaseBtnTitle:          Add torrent to database

# the release page
ReleasePageTitle name@Text: #{name} — Release
DeletedReleaseSuccess:       Release has been deleted...
ReleaseFeedBtnCaption:       Feed
ReleaseFeedBtnTitle:         Copy this URL to RSS/Atom feed and paste in your feed reader
DescriptionTab:              Description
NoDescriptionLbl:            Author probably do not added any descriptions yet...
MetadataTab:                 Metadata
EditDescBtnCaption:          Description
EditDescBtnTitle:            Change release name or description
EditMetaBtnCaption:          Metadata
EditMetaBtnTitle:            Change torrent file fields
## the release page - maintainer tab
DeleteBtnCaption:            Delete
DeleteBtnTitle:              Remove this release from tracker
## the release page - download bar
DownloadBarText:             Get this torrent via
TorrentBtnCaption:           Torrent
TorrentBtnTitle:             Get torrent file
MagnetBtnCaption:            Magnet
MagnetBtnTitle:              Open magnet link (recommended)
## the release discussion widget
DiscussionPageTitle name@Text: #{name} — Discussion
HdrComments:                 Comments
HdrNoComments:               No comments
AddCommentBtn:               Add comment
AddCommentSuccess:           Comment has been added...

# torrent list widget
## thead
ReleaseListHashColCaption:   Hash
ReleaseListHashColTitle:     Magnet link hash sum
ReleaseListNameColCaption:   Name
ReleaseListNameColTitle:     Release name
ReleaseListSizeColCaption:   Size
ReleaseListSizeColTitle:     Total size of torrent files
ReleaseListAuthorColCaption: Author
ReleaseListAuthorColTitle:   Uploaded by
## tbody
ReleaseListTitle:            Go to release description and discussion
ReleaseListAuthorTitle:      Go to author profile
ReleaseListMagnetLink:       Download using magnet link

# the edit description page
EditDescriptionPageTitle name@Text: #{name} ­ Edit description
EditDescriptionLegend:       Edit release description...
DescriptionUpdateSuccess:    Description has been updated...
NameLabel:                   Name
DescriptionLabel:            Description

# the edit metadata page
EditMetadataPageTitle:       Edit release metadata
MetadataUpdateSuccess:       Metadata has been updated...
EditMetadataLegend:          Edit torrent metadata...
EditMetadataCommentFieldLabel: Comment
AnnounceLabel:               Announce
AnnounceTooltip:             TODO tooltip
AnnounceListLabel:           Announce list
AnnounceListTooltip:         TODO tooltip
CommentLabel:                Comment
CommentTooltip:              TODO tooltip
CreatedByLabel:              Created by
CreatedByTooltip:            TODO Name of software by which produced this file
CreationDateLabel:           Creation date
CreationDateTooltip:         TODO tooltip
EncodingLabel:               Encoding
EncodingTooltip:             TODO tooltip
PublisherURLLabel:           Publisher URL
PublisherURLTooltip:         TODO tooltip

# help page
HelpPageTitle:               Help — Bitidx