AppName: Bitidx

# general form buttons
BackBtnCaption:   Back
BackBtnTitle:     All changes will be lost
CancelBtnCaption: Cancel
CancelBtnTitle:   Cancel current changes
SaveBtnCaption:   Save
SaveBtnTitle:     Save current changes

# default layout

## header
NavSearchPlaceholder: Search by name and description...
NavSearchBtn:  Search
NavAddBtn:     Add
NavSigninBtn:  Sign in
NavSignoutBtn: Sign out

## footer
FooterHomeBtn:   Home
FooterHelpBtn:   Help
FooterSourceBtn: Source
FooterIssuesBtn: Issues

# user
## permissions
LoginRequired:           You need to login to perform this action
PermissionDeniedEdit:    You need editor privileges for this action
PermissionDeniedComment: You need commenter privileges for this action

## user profile
EditProfileBtnCaption: Редактировать профиль
EditProfileBtnTitle:   TODO
## user edit profile
BackToProfileBtnCaption: Back to profile
EditUserLegend:  Edit user info...
EditUserSuccess: Profile has been modified...

# search
NoResults: No results

# the release page
AddReleaseSuccess:     Release has been added...
DeletedReleaseSuccess: Release has been deleted...
ReleaseFeedBtnCaption: Feed
ReleaseFeedBtnTitle:   Copy this URL to RSS/Atom feed and paste in your feed reader
DescriptionTab:    Description
NoDescriptionLbl:  Author probably do not added any descriptions yet...
MetadataTab:       Metadata
EditDescBtnCaption: Description
EditDescBtnTitle:   Change release name or description
EditMetaBtnCaption: Metadata
EditMetaBtnTitle:   Change torrent file fields

## the release page - maintainer tab
DeleteBtnCaption:  Delete
DeleteBtnTitle:    Remove this release from tracker

## the release page - download bar
DownloadBarText:   Get this torrent via
TorrentBtnCaption: Torrent
TorrentBtnTitle:   Get torrent file
MagnetBtnCaption:  Magnet
MagnetBtnTitle:    Open magnet link (recommended)

# discussion widget
HdrComments:    comments
HdrNoComments:  no comments
AddCommentBtn:  Add comment
AddCommentSuccess: Comment has been added...

# torrent list widget
ListHashCol:   Hash
ListNameCol:   Name
ListSizeCol:   Size
ListAuthorCol: Author

# the edit description page
EditDescriptionLegend:    Edit release description...
DescriptionUpdateSuccess: Description has been updated...

# the edit metadata page
MetadataUpdateSuccess: Metadata has been updated...
EditMetadataLegend: Edit torrent metadata...
EditMetadataCommentFieldLabel: Comment
AnnounceLabel:       Announce
AnnounceTooltip:     TODO tooltip
AnnounceListLabel:   Announce list
AnnounceListTooltip: TODO tooltip
CommentLabel:        Comment
CommentTooltip:      TODO tooltip
CreatedByLabel:      Created by
CreatedByTooltip:    TODO Name of software by which produced this file
CreationDateLabel:   Creation date
CreationDateTooltip: TODO tooltip
EncodingLabel:       Encoding
EncodingTooltip:     TODO tooltip
PublisherURLLabel:   Publisher URL
PublisherURLTooltip: TODO tooltip
