# form buttons
BackBtnCaption:              Назад
BackBtnTitle:                Все изменения будут потеряны
CancelBtnCaption:            Отменить
CancelBtnTitle:              Отменить существующие изменения
SaveBtnCaption:              Сохранить
SaveBtnTitle:                Сохранить текущую версию

# default layout

## header
NavSearchPlaceholder:        Искать по имени и описанию...
NavSearchBtn:                Поиск
NavAddBtn:                   Добавить
NavSigninBtn:                Войти
NavSignoutBtn:               Выйти

## footer
FooterHomeBtn:               Домой
FooterHelpBtn:               Справка
FooterSourceBtn:             Исходники
FooterIssuesBtn:             Неполадки

# user
UserProfilePageTitle userName@Text: #{userName} — Информация о пользователе
UserEditPageTitle    userName@Text: #{userName} — Изменить ваш профиль
UserMissingPageTitle:        Пользователь не найден
## user profile
EditProfileBtnCaption:       Редактировать профиль
EditProfileBtnTitle:         TODO
## user edit profile
BackToProfileBtnCaption:     Вернуться к профилю
EditUserLegend:              Изменить профиль...

# search
SearchResultsPageTitle query@Text: Результаты поиска для #{query} — Bitidx
SearchNoQueryPageTitle:      Поиск — Bitidx
NoResults:                   Поиск не дал результатов

# error pages
InvalidTorrentPageTitle:     Торрент файл не корректен
AlreadyExistPageTitle:       Торрент уже существует
FormFailurePageTitle:        Вы ввели что-то не то...
NotFoundPageTitle:           Ничего не найдено...

# the release add page
AddReleasePageTitle:         Добавить торрент — Bitidx
AddReleaseSuccess:           Торрент был успешно добавлен...

# the release page
ReleasePageTitle name@Text: #{name}
DescriptionTab:              Oписание
MetadataTab:                 Метаданные
NoDescriptionLbl:            Автор все ещё не добавил описание раздачи...
EditDescBtnCaption:          Описание
EditDescBtnTitle:            Изменить имя и описание раздачи
EditMetaBtnCaption:          Метаданные
EditMetaBtnTitle:            Изменить поля торрент файла

## the release page - maintainer tab
DeleteBtnCaption:            Удалить
DeleteBtnTitle:              Удалить эту раздачу

## the release page - download bar
DownloadBarText:             TODO
TorrentBtnCaption:           Torrent
TorrentBtnTitle:             TODO
MagnetBtnCaption:            Magnet
MagnetBtnTitle:              Перейти по magnet-ссылке (предпочтительно)

# discussion widget
HdrComments:                 Комментарии
HdrNoComments:               Нет комментариев
AddCommentBtn:               Добавить комментарий

# torrent list widget
## thead
ReleaseListHashColCaption:   Хеш
ReleaseListHashColTitle:     TODO
ReleaseListNameColCaption:   Имя
ReleaseListNameColTitle:     Release name
ReleaseListSizeColCaption:   Размер
ReleaseListSizeColTitle:     Полный размер раздачи
ReleaseListAuthorColCaption: Автор
ReleaseListAuthorColTitle:   Кем опубликовано
## tbody
ReleaseListTitle:            Перейти к описанию раздачи
ReleaseListAuthorTitle:      Перейти к профилю автора

# the edit description page
EditDescriptionPageTitle name@Text: #{name} ­ Редактировать описание
EditDescriptionLegend:       Изменить описание раздачи...
DescriptionUpdateSuccess:    Описание раздачи было успешно обновлено.
NameLabel:                   Имя
DescriptionLabel:            Описание

# the edit metadata page
EditMetadataPageTitle:       Редактировать метаданные
EditMetadataLegend:          Изменить метаданные .torrent файла...

# help page
HelpPageTitle: Помощь — Bitidx
