# form buttons
BackBtnCaption:   Назад
BackBtnTitle:     Все изменения будут потеряны
CancelBtnCaption: Отменить
CancelBtnTitle:   Отменить существующие изменения
SaveBtnCaption:   Сохранить
SaveBtnTitle:     Сохранить текущую версию

# default layout

## header
NavSearchBtn:  Поиск
NavAddBtn:     Добавить
NavSigninBtn:  Войти
NavSignoutBtn: Выйти

## footer
FooterHomeBtn:   Домой
FooterHelpBtn:   Справка
FooterSourceBtn: Исходники
FooterIssuesBtn: Неполадки

# user
## user profile
EditProfileBtnCaption: Редактировать профиль
EditProfileBtnTitle:   TODO
## user edit profile
BackToProfileBtnCaption: Вернуться к профилю
EditUserLegend:  Изменить профиль...

# the release page
DescriptionTab: Oписание
MetadataTab:    Метаданные
NoDescriptionLbl:  Автор все ещё не добавил описание раздачи...
EditDescBtnCaption: Описание
EditDescBtnTitle:   Изменить имя и описание раздачи
EditMetaBtnCaption: Метаданные
EditMetaBtnTitle:   Изменить поля торрент файла

## the release page - maintainer tab
DeleteBtnCaption:  Удалить
DeleteBtnTitle:    Удалить эту раздачу

## the release page - download bar
DownloadBarText:   TODO
TorrentBtnCaption: Torrent
TorrentBtnTitle:   TODO
MagnetBtnCaption:  Magnet
MagnetBtnTitle:    Открыть magnet-ссылку (предпочтительно)

# discussion widget
HdrComments:    комментарии
HdrNoComments:  нет комментариев
AddCommentBtn:  Добавить комментарий

# torrent list widget
ListHashCol:   Хеш
ListNameCol:   Имя
ListSizeCol:   Размер
ListAuthorCol: Автор

# the edit description page
EditDescriptionLegend: Изменить описание раздачи...

# the edit metadata page
EditMetadataLegend: Изменить метаданные .torrent файла...